environment: &env
- PYTHONUNBUFFERED=1
- PYTHONDONTWRITEBYTECODE=1
- TERM=xterm-256color

nginx:
  image: mozillapayments/nginx
  command: nginx -c /etc/nginx/nginx.conf -g "daemon off;"
  environment: *env
  ports:
    - '80:80'
    - '8000:8000'

service:
  image: mozillamarketplace/payments-service
  command: supervisord -n -c /srv/payments-service/docker/supervisor.conf
  environment:
  - PYTHONUNBUFFERED=1
  - PYTHONDONTWRITEBYTECODE=1
  - TERM=xterm-256color
  - EMAIL_URL_ROOT
  - SERVICE_EMAIL_BACKEND
  - SERVICE_EMAIL_HOST
  - SERVICE_EMAIL_HOST_USER
  - SERVICE_EMAIL_HOST_PASSWORD
  - SERVICE_FXA_CREDENTIALS
  - SERVICE_FXA_OAUTH_URL
  hostname: payments-service
  working_dir: /srv/payments-service

solitude:
  image: mozillamarketplace/solitude
  command: supervisord -n -c /srv/solitude/bin/docker/supervisor.conf
  environment:
  - PYTHONUNBUFFERED=1
  - PYTHONDONTWRITEBYTECODE=1
  - TERM=xterm-256color
  - BRAINTREE_MERCHANT_ID
  - SOLITUDE_BRAINTREE_PROXY=http://solitude-auth:2603/v1/braintree
  hostname: solitude
  working_dir: /srv/solitude

auth:
  image: mozillapayments/solitude-auth
  command: supervisord -n -c /srv/auth/conf/supervisor.conf
  environment:
  - PYTHONUNBUFFERED=1
  - PYTHONDONTWRITEBYTECODE=1
  - TERM=xterm-256color
  - BRAINTREE_PUBLIC_KEY
  - BRAINTREE_PRIVATE_KEY
  hostname: auth
  working_dir: /srv/auth

mysql:
  image: mozillamarketplace/mysql-service
  environment: *env

postgres:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

# FxA storage server.
kinto:
  image: kinto/kinto-server
  ports:
   - "8888:8888"
  environment:
    CLIQUET_SESSION_URL: postgres://postgres:postgres@db/postgres
    CLIQUET_STORAGE_URL: postgres://postgres:postgres@db/postgres

ui:
  image: mozillapayments/payments-ui

example:
  image: mozillapayments/payments-example

logs:
  build: ../docker/logs
